// Поиск пользователя по имени
GET http://localhost:1234/users?username=Bedon

{}
###
// Поиск польщователя по ID
GET http://localhost:1234/users/
Content-Type: application/json

{}

###

// Поиск польщователя по ID
GET http://localhost:1234/users/9
Content-Type: application/json

{}

###
// Регистрация пользователя для дальнейшей провреки авторизации

POST http://localhost:1234/users/
Content-Type: application/json

{
    "firstname": "Setgon",
    "lastname": "Carbon",
    "username": "Bedon",
    "role": "client",
    "email": "Bedon@example.com",
    "password": "Vertu123"
}
###

// Проверка авторизации пользователя
POST http://localhost:1234/auth
Content-Type: application/json

{
  "username": "Bedon",
  "password": "Vertu123"
}
###

// Проверка удаления пользователя
DELETE http://localhost:1234/users/58
Content-Type: application/json
###

// Проверка создания нового пользователя
POST http://localhost:1234/users/
Content-Type: application/json

{
  "firstname": "Сергей",
  "lastname": "Суриков",
  "username": "Noodle",
  "role": "client",
  "email": "Noodle@example.com",
  "password": "Noo123"
}
###