GET http://localhost:1234/users/
Content-Type: application/json

{}

###

GET http://localhost:1234/users/9
Content-Type: application/json

{}

###
POST http://localhost:1234/users/
Content-Type: application/json

{
  "firstname": "Ivan",
  "lastname": "Plekhanov",
  "username": "HeyTolstiy",
  "role": "client",
  "Email": "heytolty2@example.com"
}

###
POST http://localhost:1234/users/
Content-Type: application/json

{
  "firstname": "Анна",
  "lastname": "Смирнова",
  "username": "FatANN",
  "role": "client",
  "email": "anna456@example.com"
}


###

PUT http://localhost:1234/users/10
Content-Type: application/json

{"firstname": "Новое имя", "lastname": "Новая фамилия", "email": "newemail@example.com"}
###

PATCH http://localhost:1234/users/10
Content-Type: application/json

{
  "firstname": "Веня"
}


###

DELETE http://localhost:1234/users/14
Content-Type: application/json

###
