GET http://localhost:1234/users/
Content-Type: application/json

{}

###

GET http://localhost:1234/users/9
Content-Type: application/json

{}

###
POST http://localhost:1234/users/
Content-Type: application/json

{
  "firstname":    "Иван",
  "lastname": "Плеханов",
  "role": "client",
  "Email":   "ivan123@example.com"
}


###

PUT http://localhost:1234/users/10
Content-Type: application/json

{"firstname": "Новое имя", "lastname": "Новая фамилия", "email": "newemail@example.com"}
###

PATCH http://localhost:1234/users/10
Content-Type: application/json

{
  "firstname": "Веня"
}


###

DELETE http://localhost:1234/users/1
Content-Type: application/json

###
